### ISSUE TITLE
Log spam when publishing unroutable messages

### ISSUE THREAD

**Issue by skazazes-work** [mosquito/aio-pika#411]
I'm getting aggressive message output from aio-pika when publishing messages that are not routable. For my use case this is anticipated and okay behavior on the given exchange. Is there any way to disable these messages?

`Unhandled message DeliveredMessage(delivery=<pamqp.specification.Basic.Return object at 0x164b16fbd80>, header=<pamqp.header.ContentHeader object at 0x00000164B16D7BB0>, body=b'', channel=<Channel: "1">) returning`

I'm fairly certain the output is a result of messages that cannot be routed, as I can reproduce the issue by removing a binding manually in the management UI while the application is running. Any advice would be appreciated as I cannot seem to even find the source of the messages in aio-pika's code.

**Comment by skazazes-work** [comment]
I should clarify, the message output is in the console, and does not use my applications log formatted. The issue is not with AMQP message's

**Comment by mosquito** [comment]
Just add `mandatory=False` on publish

**Comment by skazazes-work** [comment]
Thanks for the info.
I [opened a PR](https://github.com/mosquito/aio-pika/pull/412) that adds some more detail to the docstring for the Exchange.publish method

**Comment by pfribourg-ias** [comment]
Hi here,
on the same topic, how can we make sure publish() throw an exception when routing_key does not exist ?

**Comment by mosquito** [comment]
@pfribourg-ias What decision do you expect from me? I can teach you how to disable logs.

This message in the log says that for some reason the broker sent a message or frame that no one will ever process, this is most likely due to an error, therefore, as I advised earlier, the correct way to solve this, in my opinion , is to add a flag `mandatory=False` if you really do not mind about this message might be dropped.

**Comment by pfribourg-ias** [comment]
Hi @mosquito thanks for you quick reply.

What I was claiming is publish() method to throw an exception when the routing is not correct.
Eg. if I publish a message to a queue that does not exist, then I would assume that publish throw me an exception with the same error that is currently printed the logs, for now, the method return None silently and I have no way to be aware that the message was tried to be send to an not existing queue.

**Comment by mosquito** [comment]
@pfribourg-ias Unfortunately, at the publishing stage, there is no correct way to make sure that the message did not return, since the message can return in an hour or tomorrow (e.g. DLX), in order to capture returned messages, you have to register a callback via `channel.return_callbacks.add(... ..)`

For example, if you want to implement the RPC pattern, it's already [implemented for you](https://aio-pika.readthedocs.io/en/latest/patterns.html#rpc). This implementation raises an exception `MessageProcessError` for all returned back from broker messages exactly to the function that is waiting for a response call result.
