### ISSUE TITLE
Number of connections

### ISSUE THREAD

**Issue by wangjianweiwei** [mosquito/aio-pika#422]
I use aio-pika in python-socketio. Now the number of connections to rabbitmq continues to increase. I'm not sure what the problem is.

Here are some information I can provide.

**version：**
aio-pika  6.8.0
rabbitmq  3.5.7

**rabbitmq connections：**
![image](https://user-images.githubusercontent.com/41533289/136517337-2649dcd8-50aa-4bdb-967c-1460f2c55c5b.png)

**output log：**
```log
Closing channel <Channel: "1"> because RPC call <pamqp.specification.Exchange.Declare object at 0x7f5d509379e0> cancelled
Closing channel <Channel: "1"> because RPC call <pamqp.specification.Confirm.Select object at 0x7f5d517500d0> cancelled
Closing channel <Channel: "1"> because RPC call <pamqp.specification.Channel.Open object at 0x7f90b5c284f0> cancelled
```

Through client_properties, it can be reflected on connections that the increasing connections are established by publishers.

code
```python
@retry()
async def _publish(self, data):
    connection = await self._connection(vvvv="publish")
    channel = await self._channel(connection)
    exchange = await self._exchange(channel)
    await exchange.publish(
        aio_pika.Message(body=pickle.dumps(data),
                         delivery_mode=aio_pika.DeliveryMode.PERSISTENT),
        routing_key='*'
    )
    await connection.close()
```

I have no idea now. I have no way to start. 😔
I also hope to correct the problem.🙏

**Comment by aktentasche** [comment]
Hi, not sure if you could solve your issue in the mean time but I am facing a similar problem.

`Closing channel <Channel: "1" at 0x7f979b285850> because RPC call <Queue.Declare object at 0x7f979b206110> cancelled`

which happens...

```
    async def listen(self):
        await self._connect()
        async with self._connection:
            channel: AbstractChannel = await self._connection.channel()

            # here
            queue: AbstractQueue = await channel.declare_queue(
                self._queue_name, auto_delete=True
            )
...
```

For me the issue actually occured when I changed from ensure_future to create_task, so this works:

`asyncio.ensure_future(self.listen())`

but this does not and throws the "cancelled" error above:

`asyncio.create_task(self.listen())`

I have to admit I don't yet really understand the difference between the two. Maybe this helps you circling in on your issue. Good luck!
