### ISSUE TITLE
Prevent Sigint to shutdown the connection - graceful shutdown

### ISSUE THREAD

**Issue by Mokto** [mosquito/aio-pika#471]
I'm trying to manually implement Graceful shutdown so that my consumer finishes handling the message (while preventing any additional incoming message to arrive) gracefully. Any way to do that?

My code so far:
```
       self._rmq_connection = await aio_pika.connect_robust(
            host=RABBITMQ_HOST,
            port=RABBITMQ_PORT,
            login=RABBITMQ_USER,
            password=RABBITMQ_PASSWORD,
        )
        self._channel = self._rmq_connection.channel()
        await self._channel.initialize()
        self._queue = await self._channel.declare_queue(
            self.__prefixed_name(queue_name), durable=True
        )
        await self._queue.consume(cb)
```

And on shutdown i have something like this:
```

            while is_processing_queue_message:
                logger.info(
                    "Still processing messaging. Waiting before closing the connection..."
                )
                await asyncio.sleep(5)
                break

            await self._rmq_connection.close()
```

Unfortunately :
1. I have to find a way to define `is_processing_queue_message` by myself. Not too big of a deal but doesn't prevent new incoming message from getting through
2. More importantly, the connection is immediately closed by the aio pika library and the messages are immediately sent to "Ready".

Thanks!

**Comment by mosquito** [comment]
For RabbitMQ the case that you will close the connection before you have time to process the messages is normal, but if you want to be sure, then I would advise you to make several modifications to your code.

First of all you should save the `queue.consume(...)` result. It's called a Consumer Tag and you may `.cancel(...)` consuming using this. After that incoming messages flow will stops but you still may to acknowledge received messages.

Now about the most difficult part, about how to understand that all messages were processed in your code. Since the code between receiving the message and calling the confirmation is completely under your control, the library will not be able to provide any mechanism to track the end of processing. I would recommend you to use, for example, `set` in which you will place messages upon receipt and delete upon confirmation, emptying this `set` will mean, in this case, the end of processing.

Also, you should be sure that `qos` is set for the channel.

Also have to note, I don't recommend initializing the channel via the `.initialize()` method. Use the syntax `channel = await connection.channel()`.

**Comment by Mokto** [comment]
Thanks for your answer!

1. Perfect, cancel seems to be a good solution for my first issue (preventing additional incoming messages).
2. I did set the qos already but wanted my snippet to be as clean as possible.

3.
About `.initialize()`, I had to do it because of typings :
- `await self._rmq_connection.channel()` returns an AbstractChannel
- `self._rmq_connection.channel()` returns a RobustAbstractChannel, the one i'm using in my class

I think both are doing the same?

4. The main issue is still here though, something inside the library is killing the rabbitmq connection by itself when receiving a SIGINT (so I can't even really test `cancel`). I don't see any way to intercept it, cancel, wait for the messages to be taken care of, and THEN kill the rabbitmq connection myself

**Comment by mosquito** [comment]
Not it's not a truth, the connection doesn't catch any signals.

```python
import asyncio
import os
import signal

from aio_pika import connect_robust


async def main():
    connect = await connect_robust()
    loop = asyncio.get_running_loop()
    try:
        loop.call_later(1, os.kill, os.getpid(), signal.SIGINT)
        await asyncio.sleep(5)
    except asyncio.CancelledError as e:
        print("Is closed?", connect.is_closed)
        await connect.close(e)
        print("Connection has been closed.")
        raise


asyncio.run(main())
```

**Comment by Mokto** [comment]
My use case is this one:

```

import asyncio
import os
import signal

from aio_pika import connect_robust


async def main():

    try:
        connect = await connect_robust()
        channel = await connect.channel()
        print("channel open", channel)

        loop = asyncio.get_running_loop()
        loop.call_later(10, os.kill, os.getpid(), signal.SIGINT)
        await asyncio.sleep(10000000000000000000000000)

    except (KeyboardInterrupt, asyncio.CancelledError):
        print("CLOSING")
        await asyncio.sleep(10)
        print("Closed")


asyncio.run(main())

```

If I do Ctrl-C or wait 10 seconds for the SIGINT signal to be sent to the process, immediately when I enter the except `except (KeyboardInterrupt, asyncio.CancelledError):`, I can see the channel is not there anymore in the RabbitMQ management webapp.

**Comment by mosquito** [comment]
So let's wait your tasks here.

Actually I would solve it using [`aiomisc.Service`](https://aiomisc.readthedocs.io/en/latest/services.html) if I were you.

**Comment by Mokto** [comment]
Amazing, it works now!

Thanks for your help 👍
