### ISSUE TITLE
Deplete All CPU When get message from "queue.get" 

### ISSUE THREAD

**Issue by strongbugman** [mosquito/aio-pika#477]
I write some code like :
```python
            while self.running:
                try:
                    message = await queue.get(timeout=self.timeout)
                    if message:
                        await self.on_message_receive(message.body, message)
                except aio_pika.exceptions.QueueEmpty:
                    pass
```
It worked well but depleted all CPU resourse:

![image](https://user-images.githubusercontent.com/16114285/179138586-5a5fede0-9f85-4a5f-ac9c-b637168b06f5.png)

Does it meet your expectations? Or there is some thing I missed？

PS: I use this solution for now:
```python
....
                except aio_pika.exceptions.QueueEmpty:
                    await asyncio.sleep(0.1)
....
````

**Comment by mosquito** [comment]
Your code make useless workload to the rabbitmq. Your code send frame each `.get()` and receive an answer each iteration, instead of send consume frame and awaiting incoming messages. This make unexpected workload to the server. You should rewrite it using consume or `async for queue.iterator()`. 

Also I recommend configure QoS for optimize memory consumption.

**Comment by strongbugman** [comment]
I got it, the `queue.get` confused me, thx.
