### ISSUE TITLE
RPCs: Exceptions are serialized to the client

### ISSUE THREAD

**Issue by dvf** [mosquito/aio-pika#502]
Using the RPC module, I've noticed that Exceptions are being swallowed and serialized and propagated to the caller. 
Is there any way to have the exception also appear in the output for the host (where the RPC lives)?

**Comment by mosquito** [comment]
@dvf [the pickle-based RPC](https://github.com/mosquito/aio-pika/blob/master/aio_pika/patterns/rpc.py#L45) the exception might be serialised and deserialised as well (see [this test for example](https://github.com/mosquito/aio-pika/blob/master/tests/test_rpc.py#L42-L43)). Since the pickle is not safe to use in an untrusted environment, there are alternative implementations using JsonRPC which raises the special exception [JsonRPCError](https://github.com/mosquito/aio-pika/blob/master/aio_pika/patterns/rpc.py#L418-L419).

Could you please provide your code sample for double-check this?

**Comment by dvf** [comment]
For anyone in a similar position, I ended up doing this:

```python
from aio_pika.patterns import JsonRPC


class JsonRPCWithLocalExceptions(JsonRPC):
    def serialize_exception(self, exception: Exception) -> Any:
        # Log locally
        logger.exception(exception)
        return {
            "error": {
                "type": exception.__class__.__name__,
                "message": repr(exception),
                "args": exception.args,
            },
        }
```

```python
async def foo():
    rpc = await JsonRPCWithLocalExceptions.create(channel)
    ...
```
